import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Logo } from "../components";
const Home: NextPage = () => {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="flex flex-col md:flex-row lg:flex-row xl:flex-row w-full h-full">
          <div className="p-4 flex w-full h-full items-center justify-center flex-col">
            <Logo width={30} height={30} />
            <p className="text-5xl mb-1">dapper designer</p>
            <p className="text-xl mt-2">React | NextJS | TailwindCSS</p>
          </div>

          <div className={styles.bottom}>
            <svg
              data-name="Layer 1"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 1200 120"
              preserveAspectRatio="none"
            >
              <path
                d="M985.66,92.83C906.67,72,823.78,31,743.84,14.19c-82.26-17.34-168.06-16.33-250.45.39-57.84,11.73-114,31.07-172,41.86A600.21,600.21,0,0,1,0,27.35V120H1200V95.8C1132.19,118.92,1055.71,111.31,985.66,92.83Z"
                className={styles.bottom_fill}
              ></path>
            </svg>
          </div>
        </main>
      </div>
    </>
  );
};

export default Home;
